# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "One"
license = "MIT"
licenselink = "https://github.com/KingBright/One/blob/master/LICENSE.md"
description = "single page hugo theme"
homepage = "https://github.com/KingBright/One"
tags = ["clean", "spa", "Hugo theme"]
features = ["", ""]
min_version = 0.15

[author]
  name = "King Bright"
  homepage = "http://kingbright.name"
